FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:224 in lock_acquire(): assertion `!lock_held_by_current_thread (lock)' failed.
Call stack: 0x800421875c 0x800420accb 0x800421e370 0x800421c4c9 0x80042073b0 0x800421dca1 0x800421d7cd 0x8004209714 0x8004209b32 0x800421e9dc 0x800421de49 0x800421da42 0x800421d842 0x400102 0x400180 0x400c21
Translation of call stack:
0x000000800421875c: debug_panic (lib/kernel/debug.c:32)
0x000000800420accb: lock_acquire (threads/synch.c:227)
0x000000800421e370: close (userprog/syscall.c:305)
0x000000800421c4c9: process_exit (userprog/process.c:313)
0x00000080042073b0: thread_exit (threads/thread.c:345)
0x000000800421dca1: fork (userprog/syscall.c:135)
0x000000800421d7cd: page_fault (userprog/exception.c:146)
0x0000008004209714: intr_handler (threads/interrupt.c:352)
0x0000008004209b32: intr_entry (threads/intr-stubs.o:?)
0x000000800421e9dc: filesys_create (filesys/filesys.c:67 (discriminator 3))
0x000000800421de49: create (userprog/syscall.c:167)
0x000000800421da42: syscall_handler (userprog/syscall.c:81)
0x000000800421d842: no_sti (userprog/syscall-entry.o:?)
0x0000000000400102: (unknown)
0x0000000000400180: (unknown)
0x0000000000400c21: (unknown)
